<#
DWP Temp File Cleanup (PowerShell 5.1)

Purpose:
- Safely clean temp files on Windows endpoints.
- Provide dry-run visibility before any change.
- Preserve rollback data by moving files to a quarantine area.

Safety and behavior:
- Per-file try/catch handling prevents one failure from stopping the run.
- Locked files are skipped and logged.
- Idempotent behavior: reruns skip already-moved/deleted files.
#>

[CmdletBinding(DefaultParameterSetName = 'Cleanup')]
param(
    # Runs discovery only and prints/logs files that would be archived.
    [Parameter(ParameterSetName = 'Cleanup')]
    [switch]$DryRun,

    # Targets files older than this many days. Default 0 means any file older than now.
    [Parameter(ParameterSetName = 'Cleanup')]
    [ValidateRange(0, 3650)]
    [int]$OlderThanDays = 0,

    # One or more root paths to scan recursively for temp files.
    [Parameter(ParameterSetName = 'Cleanup')]
    [string[]]$TargetPaths = @($env:TEMP, "$env:WINDIR\Temp"),

    # Root folder used to store archived files for rollback.
    [Parameter(ParameterSetName = 'Cleanup')]
    [string]$QuarantineRoot = "$env:ProgramData\DWP\TempCleanup\Quarantine",

    # Rollback mode switch.
    [Parameter(ParameterSetName = 'Rollback', Mandatory = $true)]
    [switch]$Rollback,

    # Manifest CSV generated by a prior cleanup run.
    [Parameter(ParameterSetName = 'Rollback', Mandatory = $true)]
    [ValidateNotNullOrEmpty()]
    [string]$ManifestPath,

    # Optional path to write logs. Defaults to a Logs folder beside this script.
    [string]$LogRoot = (Join-Path -Path $PSScriptRoot -ChildPath 'Logs')
)

$ErrorActionPreference = 'Stop'

# Section: Initialize run metadata and log file paths.
# Creates a timestamped log file and prepares in-memory summary counters.
$runTimestamp = Get-Date -Format 'yyyyMMdd_HHmmss'
$runId = [guid]::NewGuid().ToString()
$scriptName = 'DWP_TempFile_Cleanup'

if (-not (Test-Path -LiteralPath $LogRoot)) {
    New-Item -Path $LogRoot -ItemType Directory -Force | Out-Null
}

$logFile = Join-Path -Path $LogRoot -ChildPath ("{0}_{1}.log" -f $scriptName, $runTimestamp)

$summary = [ordered]@{
    Mode                 = $PSCmdlet.ParameterSetName
    DryRun               = [bool]$DryRun
    OlderThanDays        = $OlderThanDays
    ScannedFiles         = 0
    EligibleFiles        = 0
    ArchivedFiles        = 0
    RestoredFiles        = 0
    SkippedLocked        = 0
    SkippedMissing       = 0
    SkippedExisting      = 0
    Errors               = 0
    StartTime            = (Get-Date)
    EndTime              = $null
    DurationSeconds      = $null
    LogFile              = $logFile
    ManifestPath         = $null
}

# Section: Logging helper.
# Writes a timestamped line to console and to the run log file.
function Write-Log {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Message,
        [ValidateSet('INFO', 'WARN', 'ERROR')]
        [string]$Level = 'INFO'
    )

    $timestamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
    $line = "[{0}] [{1}] {2}" -f $timestamp, $Level, $Message
    Write-Host $line
    Add-Content -LiteralPath $logFile -Value $line
}

# Section: Locked-file detector.
# Tries to open the file exclusively; if this fails with IO exception, treat as locked.
function Test-FileLocked {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path
    )

    try {
        $stream = [System.IO.File]::Open($Path, [System.IO.FileMode]::Open, [System.IO.FileAccess]::ReadWrite, [System.IO.FileShare]::None)
        $stream.Close()
        return $false
    }
    catch [System.IO.IOException] {
        return $true
    }
    catch {
        # Non-IO failures are handled by the caller's per-file try/catch logic.
        return $false
    }
}

# Section: Cleanup mode implementation.
# Scans target folders, filters by age, and archives files into quarantine for rollback.
function Invoke-Cleanup {
    $cutoff = (Get-Date).AddDays(-1 * $OlderThanDays)
    $runQuarantineRoot = Join-Path -Path $QuarantineRoot -ChildPath $runId
    $manifestPath = Join-Path -Path $runQuarantineRoot -ChildPath 'manifest.csv'
    $summary.ManifestPath = $manifestPath

    if (-not $DryRun) {
        New-Item -Path $runQuarantineRoot -ItemType Directory -Force | Out-Null
    }

    $manifestRows = New-Object System.Collections.Generic.List[object]

    Write-Log -Message ("Cleanup started. Cutoff datetime: {0}" -f $cutoff)
    Write-Log -Message ("Target paths: {0}" -f ($TargetPaths -join '; '))

    foreach ($root in $TargetPaths) {
        if ([string]::IsNullOrWhiteSpace($root)) {
            continue
        }

        if (-not (Test-Path -LiteralPath $root)) {
            Write-Log -Level 'WARN' -Message ("Target path not found, skipping: {0}" -f $root)
            continue
        }

        Write-Log -Message ("Scanning path: {0}" -f $root)

        Get-ChildItem -LiteralPath $root -File -Recurse -Force -ErrorAction SilentlyContinue | ForEach-Object {
            $file = $_
            $summary.ScannedFiles++

            if ($file.LastWriteTime -gt $cutoff) {
                return
            }

            $summary.EligibleFiles++

            if (-not (Test-Path -LiteralPath $file.FullName)) {
                $summary.SkippedMissing++
                Write-Log -Level 'WARN' -Message ("Missing before processing, skipped: {0}" -f $file.FullName)
                return
            }

            if (Test-FileLocked -Path $file.FullName) {
                $summary.SkippedLocked++
                Write-Log -Level 'WARN' -Message ("Locked file skipped: {0}" -f $file.FullName)

                $manifestRows.Add([pscustomobject]@{
                    OriginalPath = $file.FullName
                    ArchivedPath = ''
                    Status       = 'SkippedLocked'
                    ActionTime   = (Get-Date).ToString('o')
                }) | Out-Null
                return
            }

            if ($DryRun) {
                Write-Log -Message ("DRY-RUN would archive: {0}" -f $file.FullName)

                $manifestRows.Add([pscustomobject]@{
                    OriginalPath = $file.FullName
                    ArchivedPath = ''
                    Status       = 'DryRunWouldArchive'
                    ActionTime   = (Get-Date).ToString('o')
                }) | Out-Null
                return
            }

            # Per-file error handling for archive/move action.
            try {
                $drivePrefix = $file.FullName.Substring(0, 2).Replace(':', '_')
                $relativePart = $file.FullName.Substring(2).TrimStart('\\')
                $destinationPath = Join-Path -Path $runQuarantineRoot -ChildPath (Join-Path -Path $drivePrefix -ChildPath $relativePart)
                $destinationDir = Split-Path -Path $destinationPath -Parent

                if (-not (Test-Path -LiteralPath $destinationDir)) {
                    New-Item -Path $destinationDir -ItemType Directory -Force | Out-Null
                }

                Move-Item -LiteralPath $file.FullName -Destination $destinationPath -Force
                $summary.ArchivedFiles++
                Write-Log -Message ("Archived: {0} -> {1}" -f $file.FullName, $destinationPath)

                $manifestRows.Add([pscustomobject]@{
                    OriginalPath = $file.FullName
                    ArchivedPath = $destinationPath
                    Status       = 'Archived'
                    ActionTime   = (Get-Date).ToString('o')
                }) | Out-Null
            }
            catch {
                $summary.Errors++
                Write-Log -Level 'ERROR' -Message ("Failed to archive file: {0}. Error: {1}" -f $file.FullName, $_.Exception.Message)

                $manifestRows.Add([pscustomobject]@{
                    OriginalPath = $file.FullName
                    ArchivedPath = ''
                    Status       = 'Error'
                    ActionTime   = (Get-Date).ToString('o')
                }) | Out-Null
            }
        }
    }

    if ($manifestRows.Count -gt 0) {
        if (-not $DryRun) {
            $manifestRows | Export-Csv -LiteralPath $manifestPath -NoTypeInformation -Encoding UTF8
            Write-Log -Message ("Manifest saved: {0}" -f $manifestPath)
        }
        else {
            Write-Log -Message 'Dry-run mode: no manifest file was written because no files were moved.'
        }
    }
}

# Section: Rollback mode implementation.
# Restores files from a manifest created by a prior cleanup run.
function Invoke-Rollback {
    if (-not (Test-Path -LiteralPath $ManifestPath)) {
        throw "Manifest not found: $ManifestPath"
    }

    $summary.ManifestPath = $ManifestPath
    Write-Log -Message ("Rollback started using manifest: {0}" -f $ManifestPath)

    $rows = Import-Csv -LiteralPath $ManifestPath
    foreach ($row in $rows) {
        if ($row.Status -ne 'Archived') {
            continue
        }

        $summary.EligibleFiles++

        # Per-file error handling for restore action.
        try {
            if (-not (Test-Path -LiteralPath $row.ArchivedPath)) {
                $summary.SkippedMissing++
                Write-Log -Level 'WARN' -Message ("Archived file missing, cannot restore: {0}" -f $row.ArchivedPath)
                continue
            }

            if (Test-Path -LiteralPath $row.OriginalPath) {
                $summary.SkippedExisting++
                Write-Log -Level 'WARN' -Message ("Original already exists, skipped restore to keep idempotent behavior: {0}" -f $row.OriginalPath)
                continue
            }

            $originalDir = Split-Path -Path $row.OriginalPath -Parent
            if (-not (Test-Path -LiteralPath $originalDir)) {
                New-Item -Path $originalDir -ItemType Directory -Force | Out-Null
            }

            Move-Item -LiteralPath $row.ArchivedPath -Destination $row.OriginalPath -Force
            $summary.RestoredFiles++
            Write-Log -Message ("Restored: {0} -> {1}" -f $row.ArchivedPath, $row.OriginalPath)
        }
        catch {
            $summary.Errors++
            Write-Log -Level 'ERROR' -Message ("Failed to restore file: {0}. Error: {1}" -f $row.OriginalPath, $_.Exception.Message)
        }
    }
}

# Section: Main control flow.
# Runs cleanup or rollback mode based on supplied parameter set.
try {
    Write-Log -Message ("Script started. Mode: {0}" -f $PSCmdlet.ParameterSetName)

    switch ($PSCmdlet.ParameterSetName) {
        'Cleanup'  { Invoke-Cleanup }
        'Rollback' { Invoke-Rollback }
        default    { throw 'Unknown parameter set.' }
    }
}
catch {
    $summary.Errors++
    Write-Log -Level 'ERROR' -Message ("Fatal error: {0}" -f $_.Exception.Message)
}
finally {
    # Section: Summary output.
    # Prints an end-of-run summary and writes it to the log for service-desk review.
    $summary.EndTime = Get-Date
    $summary.DurationSeconds = [math]::Round((New-TimeSpan -Start $summary.StartTime -End $summary.EndTime).TotalSeconds, 2)

    Write-Host "`n==================== Cleanup Summary ===================="
    $summary.GetEnumerator() | ForEach-Object {
        $line = "{0}: {1}" -f $_.Key, $_.Value
        Write-Host $line
        Add-Content -LiteralPath $logFile -Value $line
    }

    Write-Host "========================================================="
    Write-Host ("Log file: {0}" -f $logFile)

    if (-not $DryRun -and $summary.ManifestPath) {
        Write-Host ("Manifest path: {0}" -f $summary.ManifestPath)
    }
}
